<?php 
namespace App\Models;

use Illuminate\Database\Eloquent\Model;
//Generated By PlantUML Command
class Elector extends Model{
    public function voto(){
        return $this->belongsTo('App\Models\Voto');
    }

public function candidato(){
    return $this->belongsTo('App\Models\Candidato');
}

public function cabina(){
    return $this->belongsTo('App\Models\Cabina');
}

}